// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoesStore.Data;

#nullable disable

namespace ShoesStore.Migrations
{
    [DbContext(typeof(ShoesStoreContext))]
    [Migration("20221214165657_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShoesStore.Models.Brand", b =>
                {
                    b.Property<int>("Id_Brand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Brand"), 1L, 1);

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Brand");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("ShoesStore.Models.Comanda", b =>
                {
                    b.Property<int>("Id_Comanda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Comanda"), 1L, 1);

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data_Comenzii")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Produs")
                        .HasColumnType("int");

                    b.Property<int>("Id_User")
                        .HasColumnType("int");

                    b.Property<string>("Judet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProdusId_Produs")
                        .HasColumnType("int");

                    b.Property<string>("Tara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefon")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int?>("UserId_User")
                        .HasColumnType("int");

                    b.HasKey("Id_Comanda");

                    b.HasIndex("ProdusId_Produs");

                    b.HasIndex("UserId_User");

                    b.ToTable("Comanda");
                });

            modelBuilder.Entity("ShoesStore.Models.CosCumparaturi", b =>
                {
                    b.Property<int>("Id_Cos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Cos"), 1L, 1);

                    b.Property<int>("Cantitate")
                        .HasColumnType("int");

                    b.Property<int>("Id_Produs")
                        .HasColumnType("int");

                    b.Property<int?>("ProdusId_Produs")
                        .HasColumnType("int");

                    b.HasKey("Id_Cos");

                    b.HasIndex("ProdusId_Produs");

                    b.ToTable("CosCumparaturi");
                });

            modelBuilder.Entity("ShoesStore.Models.Detalii_Produs", b =>
                {
                    b.Property<int>("Id_Detalii")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Detalii"), 1L, 1);

                    b.Property<string>("Culoare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Produs")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Marime")
                        .HasColumnType("int");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Pret")
                        .HasColumnType("float");

                    b.Property<int?>("ProdusId_Produs")
                        .HasColumnType("int");

                    b.HasKey("Id_Detalii");

                    b.HasIndex("ProdusId_Produs");

                    b.ToTable("Detalii_Produs");
                });

            modelBuilder.Entity("ShoesStore.Models.Produs", b =>
                {
                    b.Property<int>("Id_Produs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Produs"), 1L, 1);

                    b.Property<int?>("BrandId_Brand")
                        .HasColumnType("int");

                    b.Property<int>("Id_Brand")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume_Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Produs");

                    b.HasIndex("BrandId_Brand");

                    b.ToTable("Produs");
                });

            modelBuilder.Entity("ShoesStore.Models.User", b =>
                {
                    b.Property<int>("Id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_User"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origine_User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_User");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ShoesStore.Models.Comanda", b =>
                {
                    b.HasOne("ShoesStore.Models.Produs", "Produs")
                        .WithMany()
                        .HasForeignKey("ProdusId_Produs");

                    b.HasOne("ShoesStore.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId_User");

                    b.Navigation("Produs");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShoesStore.Models.CosCumparaturi", b =>
                {
                    b.HasOne("ShoesStore.Models.Produs", "Produs")
                        .WithMany()
                        .HasForeignKey("ProdusId_Produs");

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("ShoesStore.Models.Detalii_Produs", b =>
                {
                    b.HasOne("ShoesStore.Models.Produs", "Produs")
                        .WithMany()
                        .HasForeignKey("ProdusId_Produs");

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("ShoesStore.Models.Produs", b =>
                {
                    b.HasOne("ShoesStore.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId_Brand");

                    b.Navigation("Brand");
                });
#pragma warning restore 612, 618
        }
    }
}
